# Generated by Django 4.2.10 on 2026-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIPromptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_query", models.TextField()),
                ("ai_response", models.TextField()),
                ("used_details", models.JSONField(default=dict)),
                ("execution_time_ms", models.IntegerField()),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RouteRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "locations",
                    models.JSONField(help_text="List of location IDs and order"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Duration in hours"),
                ),
                ("total_distance_km", models.FloatField(default=0)),
                (
                    "ai_reasoning",
                    models.TextField(help_text="Why this route was recommended"),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="Recommendation score 0-1"
                    ),
                ),
                ("season", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("liked", "Liked"),
                            ("neutral", "Neutral"),
                            ("disliked", "Disliked"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
