# Generated by Django 4.2.10 on 2026-03-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "Весна"),
                            ("summer", "Лето"),
                            ("autumn", "Осень"),
                            ("winter", "Зима"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duration_days", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("gastronomy", "Гастрономия"),
                            ("wine", "Вино"),
                            ("nature", "Природа"),
                            ("history", "История"),
                            ("art", "Искусство"),
                            ("adventure", "Приключения"),
                            ("wellness", "Оздоровление"),
                            ("photography", "Фотография"),
                            ("family", "Семейный отдых"),
                            ("culture", "Культура"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(default=5, help_text="1-10 preference level"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("duration_hours", models.IntegerField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
