# Generated by Django 4.2.10 on 2026-03-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("routes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeinterest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="locations",
            field=models.ManyToManyField(
                related_name="routes",
                through="routes.RouteLocation",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routelocation",
            unique_together={("route", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="routeinterest",
            unique_together={("user", "interest")},
        ),
    ]
