# Generated by Django 4.2.10 on 2026-03-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locationphoto",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="locationphoto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="best_season",
            field=models.ManyToManyField(
                related_name="locations", to="locations.season"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="locations.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="locationreview",
            unique_together={("location", "user")},
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["category", "-rating"], name="locations_l_categor_8ff40f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["featured"], name="locations_l_feature_a64c51_idx"
            ),
        ),
    ]
